# Generated by Django 3.0.5 on 2020-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0003_auto_20200521_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('imported_qty', models.IntegerField()),
                ('imported_cost', models.BigIntegerField()),
                ('sold_qty', models.IntegerField()),
                ('supplierName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ptype', models.CharField(max_length=30)),
                ('img', models.ImageField(default='default.jpg', upload_to='product_pics')),
            ],
        ),
    ]
