# Generated by Django 3.0.5 on 2020-05-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0005_auto_20200524_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imported_cost',
            new_name='Imported_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imported_qty',
            new_name='Imported_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ptype',
            new_name='Product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sold_qty',
            new_name='Sold_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplierName',
            new_name='Supplier_name',
        ),
    ]
