# Generated by Django 3.0.5 on 2020-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0006_auto_20200524_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_code',
            field=models.CharField(default='DEF000', max_length=6),
        ),
    ]
