# Generated by Django 3.0.5 on 2020-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0008_product_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Profit',
            field=models.IntegerField(default=0),
        ),
    ]
