# Generated by Django 3.0.5 on 2020-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmin', '0009_product_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='product_pics'),
        ),
    ]
